/** VMO staff email directory — all employees (managers are upgraded via VMO_APPRAISER_EMAILS on seed). */
export type DirectoryEntry = {
  first_name: string;
  last_name: string;
  department: string;
  job_title: string;
  email: string;
};

export const VMO_EMPLOYEE_DIRECTORY: DirectoryEntry[] = [
  { first_name: "Abisola", last_name: "Ojuade", department: "HR", job_title: "Human Resource Associate", email: "abisola@vmoaeros.com" },
  { first_name: "Abiodun", last_name: "Fakayejo", department: "Internal Control", job_title: "Internal Control Officer", email: "Abiodun@vmoaeros.com" },
  { first_name: "Adejoke", last_name: "Okeowo-Adediran", department: "Quality & Safety", job_title: "Quality & Safety Manager", email: "adejoke@vmoaeros.com" },
  { first_name: "Ademola", last_name: "Aremu", department: "CHL", job_title: "Operations Administrator", email: "ademolachl@gmail.com" },
  { first_name: "Ademola", last_name: "Adetoyi", department: "Operations", job_title: "Business Development Consultant", email: "Ademola@vmoaeros.com" },
  { first_name: "Adeola", last_name: "Oluwole", department: "HR", job_title: "Human Resource Assistant", email: "hiring@vmoaeros.com" },
  { first_name: "Adesewa", last_name: "Ogunkanmi", department: "Comms & IT", job_title: "Corporate Communications and Branding Assistant", email: "Adesewa@vmoaeros.com" },
  { first_name: "Adesina", last_name: "Elijah", department: "AGRO", job_title: "Food Production and Processing Lead", email: "Adesinaelijah@vmoagro.com" },
  { first_name: "Adesoji", last_name: "Adedara", department: "Finance", job_title: "Account and Finance Manager", email: "adesoji@vmoaeros.com" },
  { first_name: "Ajuma", last_name: "Udele", department: "CSE", job_title: "Cabin Service Executive", email: "ajuma@vmoaeros.com" },
  { first_name: "Alhaji", last_name: "Saidu-Suleiman", department: "Operations", job_title: "Pilot - Fixed Wings", email: "saidu@vmoaeros.com" },
  { first_name: "Aminu", last_name: "Mohammed-Maina", department: "Operations", job_title: "Pilot - Fixed Wings", email: "Aminu@vmoaeros.com" },
  { first_name: "Ayodeji", last_name: "Olofinyokun", department: "CEO'S Office", job_title: "Executive Assistant to the CEO", email: "Ayodeji@vmoaeros.com" },
  { first_name: "Ayomide", last_name: "Akinnowonu", department: "AGRO", job_title: "Crop Farm Supervisor", email: "ayomideakinnowonu@vmoagro.com" },
  { first_name: "Benjamin", last_name: "Audu", department: "Operations", job_title: "Pilot - Fixed Wing", email: "benjaminaudu@vmoaeros.com" },
  { first_name: "Blessing", last_name: "Adeyemi", department: "CSE", job_title: "Cabin Service Executive", email: "Blessingadeyemi@vmoaeros.com" },
  { first_name: "Bright", last_name: "Peter", department: "Maintainace", job_title: "Maintainance Assistant", email: "brightvmo@gmail.com" },
  { first_name: "Chidinma", last_name: "Ibeh", department: "Finance", job_title: "Finance Assistant", email: "Chidinma@vmoaeros.com" },
  { first_name: "Chibundu", last_name: "Victory", department: "Maintainace", job_title: "Maintainance Assistant", email: "victoryvmoaeros@gmail.com" },
  { first_name: "Christopher", last_name: "Nwaike", department: "Operations", job_title: "Operations Manager/Licenced Flight Dispatcher", email: "christopher@vmoaeros.com" },
  { first_name: "Cynthia", last_name: "Ngwodo", department: "Comms & IT", job_title: "Corporate Communications and Tech Supervisor", email: "cynthia@vmoaeros.com" },
  { first_name: "Damilola", last_name: "Ajina", department: "Operations", job_title: "Chief Pilot - Fixed Wing", email: "damilolaajina@vmoaeros.com" },
  { first_name: "Edeheudim", last_name: "Udofia", department: "Maintainace", job_title: "DCA - Rotary Wing Engineer", email: "edeheudim@vmoaeros.com" },
  { first_name: "Emmanuel", last_name: "Awe", department: "Maintainace", job_title: "Aircraft Maintenance Planner and Technical Records Associate", email: "emmanuel@vmoaeros.com" },
  { first_name: "Emmanuel", last_name: "Udele", department: "Maintainace", job_title: "Maintenance Admin Assistant", email: "emmanueludele@vmoaeros.com" },
  { first_name: "Emmanuel", last_name: "Uche", department: "Operations", job_title: "Operation Trainee - OJT", email: "ifebuchevmo@gmail.com" },
  { first_name: "Emmanuella", last_name: "Uuijialator", department: "HR", job_title: "Human Resource Manager", email: "emmanuella@vmoaeros.com" },
  { first_name: "Stephen", last_name: "Nixon", department: "Operations", job_title: "Technical Cordinator", email: "Nixonstephen@vmoaeros.com" },
  { first_name: "Justina", last_name: "Itodo", department: "Operations", job_title: "Operations Administrative Assistant", email: "Justinaitodo@vmoaeros.com" },
  { first_name: "Fiyinfoluwa", last_name: "Olanlokun", department: "Admin", job_title: "Administrative and Project Associate", email: "Fiyinfoluwa@vmoaeros.com" },
  { first_name: "Fred", last_name: "Chukwurah", department: "Operations", job_title: "Pilot - Fixed Wing", email: "fred@vmoaeros.com" },
  { first_name: "Funmi", last_name: "Ifanse", department: "CSE", job_title: "Cabin Service Executive Manager", email: "funmi@vmoaeros.com" },
  { first_name: "Halleluyah", last_name: "Benjamin", department: "Quality & Safety", job_title: "Quality and Safety Auditor", email: "halleluyah@vmoaeros.com" },
  { first_name: "Ibironke", last_name: "Adesanya", department: "Finance", job_title: "Senior Finance Associate", email: "Ibironkeadesanya@vmoaeros.com" },
  { first_name: "Isaac", last_name: "Kayode", department: "Admin", job_title: "Crew House Admin", email: "isaackayode@vmoaeros.com" },
  { first_name: "Magdalene", last_name: "Eyo", department: "CSE", job_title: "Cabin Service Executive", email: "magdalene@vmoaeros.com" },
  { first_name: "Martins", last_name: "Avaan", department: "Operations", job_title: "Pilot - Fixed Wing", email: "Martins@vmoaeros.com" },
  { first_name: "Michael", last_name: "Ironbar", department: "Maintainace", job_title: "Chief Engineer - Fixed Wing", email: "ironbar@vmoaeros.com" },
  { first_name: "Micheal", last_name: "Olaoye", department: "Executive Leadership", job_title: "Chief Executive Officer", email: "michaelolaoye@vmoaeros.com" },
  { first_name: "Miracle", last_name: "Uyanwanne", department: "CSE", job_title: "Cabin Service Executive", email: "Ijeoma@vmoaeros.com" },
  { first_name: "Mueez", last_name: "Abimbola", department: "Quality & Safety", job_title: "Quality and Safety Assistant", email: "Mueez@vmoaeros.com" },
  { first_name: "Okikiola", last_name: "Tijani", department: "Comms & IT", job_title: "Social Media and Content Creation Associate", email: "smm@vmoaeros.com" },
  { first_name: "Ogheneriomen", last_name: "Onoworemu", department: "Maintainace", job_title: "Maintenance Planner and Technical Records Officer", email: "ogheneriomen@vmoaeros.com" },
  { first_name: "Okoronkwo", last_name: "Sammuel", department: "Maintainace", job_title: "Maintainance Assistant", email: "samuelvmoaeros@gmail.com" },
  { first_name: "Okoase", last_name: "Bash", department: "Operations", job_title: "Pilot - Fixed Wing", email: "Okoasebash@vmoaeros.com" },
  { first_name: "Olamide", last_name: "Akintoye", department: "Comms & IT", job_title: "IT Infrastructure and Media Associate", email: "olamide@vmoaeros.com" },
  { first_name: "Olamide", last_name: "Ogunjobi", department: "Operations", job_title: "Operations Admin Associate", email: "Ayomide@vmoaeros.com" },
  { first_name: "Olatunji", last_name: "Agboola", department: "CHL", job_title: "Operations and Maintenance Associate", email: "olatunji@citygateshl.com" },
  { first_name: "Olugbenga", last_name: "Emoruwa", department: "Executive Leadership", job_title: "General Manager", email: "olugbenga@citygateshl.com" },
  { first_name: "Olugbenga", last_name: "Emoruwa", department: "Executive Leadership", job_title: "General Manager", email: "vmogeneralmanager@gmail.com" },
  { first_name: "Oluwagbenga", last_name: "Adeboye", department: "AGRO", job_title: "Livestock Farm Supervisor", email: "oluwagbenga@vmoagro.com" },
  { first_name: "Oluwaseun", last_name: "Ayodeji-cole", department: "Executive Leadership", job_title: "Chief Operating Officer", email: "seun@vmoaeros.com" },
  { first_name: "Oluwatobi", last_name: "Aremu", department: "Maintainace", job_title: "Aircraft Procurement and Stores Associate", email: "oluwatobi@vmoaeros.com" },
  { first_name: "Operations", last_name: "Department", department: "Operations", job_title: "Department", email: "ops@vmoaeros.com" },
  { first_name: "Oyindamola", last_name: "Benthomas", department: "Admin", job_title: "Admin and Facility Manager", email: "oyindamola@vmoaeros.com" },
  { first_name: "Patrick", last_name: "Onah", department: "Operations", job_title: "Pilot - Rotary Wing", email: "patrick@vmoaeros.com" },
  { first_name: "Palmer", last_name: "Akpan", department: "Maintainace", job_title: "Aircraft Maintenance Engineer - CL-601", email: "Palmerakpan@vmoaeros.com" },
  { first_name: "Peace", last_name: "Ogbu", department: "AGRO", job_title: "Executive Assistant to the GM", email: "info@vmoagro.com" },
  { first_name: "Peace", last_name: "Ogbu", department: "CHL", job_title: "Executive Assistant to the GM", email: "info@citygateshl.com" },
  { first_name: "Peter", last_name: "Yakubu", department: "Operations", job_title: "Operations Assistant & AVSEC -ABV", email: "peteryakubuvmo@gmail.com" },
  { first_name: "Praise", last_name: "Omenogor", department: "Legal", job_title: "Legal Associate", email: "praise@vmoaeros.com" },
  { first_name: "Priye", last_name: "Stephen", department: "Admin", job_title: "Front Desk and Admin Officer", email: "Priye@vmoaeros.com" },
  { first_name: "Prudent", last_name: "Ekwe", department: "AGRO", job_title: "Admin Assist", email: "prudentvmo@gmail.com" },
  { first_name: "Rabi", last_name: "Iboyi", department: "Commercial", job_title: "Commercial Supervisor", email: "commercial@vmoaeros.com" },
  { first_name: "Rasak", last_name: "Adebayo", department: "Operations", job_title: "Operations Associate/ Licenced Flight Dispatcher", email: "Adedayo@vmoaeros.com" },
  { first_name: "Saidat", last_name: "Ahmed", department: "Operations", job_title: "Operations Associate/Licenced Flight Dispatcher- ABJ", email: "saidat@vmoaeros.com" },
  { first_name: "Victor", last_name: "Dzer", department: "Operations", job_title: "Operations Trainee", email: "Victordzer@vmoaeros.com" },
  { first_name: "VMO Aero", last_name: "Official", department: "Official Email", job_title: "VMO Aero Official Email", email: "info@vmoaeros.com" },
  { first_name: "VMO Aero", last_name: "Nig Ltd", department: "Official Email", job_title: "VMO Aero Official Email", email: "vmoaeronigltd@gmail.com" },
  { first_name: "VMO Aero", last_name: "Ltd", department: "Official Email", job_title: "VMO Aero Official Email", email: "vmoaeroltd@gmail.com" },
];
